# Build & Deploy on Tag & Push
name: Github Package

on:
  push:
    tags:
      ["v*.*.*", "v*.*.*-*"]
    branches:
      ["release-4.*.*", "release-5.*.*", "release-v2.*.*", "master", "development"]
  pull_request:
    branches:
      ["release-4.*.*", "release-5.*.*", "release-v2.*.*", "master", "development"]

jobs:
  build-deploy-github:
    name: Build & Deploy to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_USERNAME
          server-password: GITHUB_TOKEN

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Delete package specific version
        uses: smartsquaregmbh/delete-old-packages@v0.4.0
        with:
          version: 2.1.0-SNAPSHOT # This should be same as in the pom.xml file,
                          # to delete only the pom specified version, not the other older versions
          names: |
            com.uci.utils
          token: ${{ secrets.TOKEN }}


      - name: Deploy
        run: mvn clean install -Pgithub deploy
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
